### ISSUE TITLE
Some buffs are not working as they should

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#186]
I was first just gonna disable the ones that didnt do anything but it turns out quite a few of them aren't working.

So far I have noticed that in my game the following buffs aren't working, either they display wrong data or aren't displayed at all.

Ammo Efficiency - Not visible

Total Dodge Chance - Not visible

Unseen Strike - Not showing correct data

Gage boost: Life steal - What is this?

**Comment by steam-test1** [comment]
Unseen Strike maybe fixed below
https://bitbucket.org/pjal3urb/gameinfomanager/commits/
Will maybe look into these, but not anytime soon
The problem is that HUDList is no longer maintained and Kamikaze94 only seems to fix certain parts of WolfHUD
Life Steal probably is gaining armor or health on kill
https://github.com/steam-test1/Payday-2-LuaJIT-Complete/blob/master/lib/modifiers/boosts/gagemodifierlifesteal.lua

**Comment by LT71** [comment]
Can correct myself and say that the total dodge chance does work, I will look into the rest and either fix them or disable them
