### ISSUE TITLE
Damage Popup question

### ISSUE THREAD

**Issue by steam-test1** [steam-test1/VPlusHUD#193]
If it ever was created
Would the HoxHUD version replace both damage popups or just one

**Comment by LT71** [comment]
I personally like the hoxhud popups the most. If you are asking if it should replace the other ones I would say yes to that since having 3 kinds of popups for damage might be a bit much. I like the wolfhud version the least as they look rather dull. 

The current glowing popup is nice since it makes killing enemies more satisfying seeing all those glowing popups.

If the hoxhud popups were to be created I think they could take the place of the others because its so similar to the glowing popups the hud already have.

 If the wolfhud popups should stay or not could be debated, I just don't like it very much and having the hoxhud styled popups and enemy health completely replace the wolfhud versions could also make vanillahud plus stand out a bit more compared to wolfhud and sydneyhud.

So yea if I understood the question correctly then my answer to that would be that many options are good but to limit them so it won't have so many different things to offer that all do the same thing.
